/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AnalysisMode = IDL.Variant({
  'receipt' : IDL.Null,
  'food' : IDL.Null,
  'carFashion' : IDL.Null,
  'translation' : IDL.Null,
  'medicalReference' : IDL.Null,
  'artLandmark' : IDL.Null,
  'generic' : IDL.Null,
  'plant' : IDL.Null,
  'bookProduct' : IDL.Null,
});
export const DetectedObject = IDL.Record({
  'name' : IDL.Text,
  'confidence' : IDL.Float64,
});
export const WebResult = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'snippet' : IDL.Text,
});
export const AnalysisResult = IDL.Record({
  'sceneDescription' : IDL.Text,
  'extractedText' : IDL.Text,
  'objects' : IDL.Vec(DetectedObject),
  'webResults' : IDL.Vec(WebResult),
});
export const Timestamp = IDL.Int;
export const Collection = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'scanIds' : IDL.Vec(IDL.Text),
});
export const DiscoveryFilter = IDL.Record({
  'sortBy' : IDL.Variant({
    'trending' : IDL.Null,
    'newest' : IDL.Null,
    'mostLiked' : IDL.Null,
  }),
  'mode' : IDL.Opt(AnalysisMode),
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'keyword' : IDL.Opt(IDL.Text),
});
export const DiscoveryScan = IDL.Record({
  'id' : IDL.Text,
  'analysisResult' : AnalysisResult,
  'title' : IDL.Opt(IDL.Text),
  'likeCount' : IDL.Nat,
  'scanId' : IDL.Text,
  'analysisMode' : AnalysisMode,
  'ownerPrincipal' : IDL.Text,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'privacy' : IDL.Variant({ 'open' : IDL.Null, 'unlisted' : IDL.Null }),
  'viewCount' : IDL.Nat,
  'imageBase64' : IDL.Text,
});
export const ScanRecord = IDL.Record({
  'id' : IDL.Text,
  'analysisResult' : AnalysisResult,
  'userId' : IDL.Principal,
  'mode' : AnalysisMode,
  'shareToken' : IDL.Opt(IDL.Text),
  'mimeType' : IDL.Text,
  'imageBase64' : IDL.Text,
  'timestamp' : Timestamp,
});
export const UserSettings = IDL.Record({
  'webSearchEnabled' : IDL.Bool,
  'historyRetentionDays' : IDL.Opt(IDL.Nat),
  'scanResultLayout' : IDL.Variant({
    'stacked' : IDL.Null,
    'compact' : IDL.Null,
    'sideBySide' : IDL.Null,
  }),
  'theme' : IDL.Variant({
    'auto' : IDL.Null,
    'dark' : IDL.Null,
    'light' : IDL.Null,
  }),
  'tagAggressiveness' : IDL.Variant({
    'aggressive' : IDL.Null,
    'subtle' : IDL.Null,
    'moderate' : IDL.Null,
  }),
  'collectionOrganizationMode' : IDL.Variant({
    'tagBased' : IDL.Null,
    'flat' : IDL.Null,
  }),
  'exportFormat' : IDL.Variant({
    'csv' : IDL.Null,
    'pdf' : IDL.Null,
    'json' : IDL.Null,
  }),
  'language' : IDL.Text,
  'resultDetailLevel' : IDL.Variant({
    'detailed' : IDL.Null,
    'compact' : IDL.Null,
    'standard' : IDL.Null,
  }),
  'defaultScanPrivacy' : IDL.Variant({
    'open' : IDL.Null,
    'unlisted' : IDL.Null,
    'onlyMe' : IDL.Null,
  }),
  'showConfidenceScores' : IDL.Bool,
  'autoSaveScans' : IDL.Bool,
});
export const VideoFrame = IDL.Record({
  'analysisResult' : IDL.Opt(AnalysisResult),
  'imageBase64' : IDL.Text,
  'frameIndex' : IDL.Nat,
  'timestamp' : IDL.Float64,
  'processed' : IDL.Bool,
});
export const VideoAnalysisJob = IDL.Record({
  'id' : IDL.Text,
  'frameInterval' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  }),
  'frameCount' : IDL.Nat,
  'analysisMode' : AnalysisMode,
  'ownerPrincipal' : IDL.Text,
  'createdAt' : Timestamp,
  'videoName' : IDL.Text,
  'frames' : IDL.Vec(VideoFrame),
});
export const TagSuggestionRequest = IDL.Record({
  'analysisResult' : AnalysisResult,
  'scanId' : IDL.Text,
  'existingTags' : IDL.Vec(IDL.Text),
  'aggressiveness' : IDL.Variant({
    'aggressive' : IDL.Null,
    'subtle' : IDL.Null,
    'moderate' : IDL.Null,
  }),
});
export const TagSuggestion = IDL.Record({
  'tag' : IDL.Text,
  'source' : IDL.Variant({ 'ai' : IDL.Null, 'user' : IDL.Null }),
  'confidence' : IDL.Float64,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addScanToCollection' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'analyzeImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(AnalysisMode)],
      [AnalysisResult],
      [],
    ),
  'createCollection' : IDL.Func([IDL.Text], [IDL.Text], []),
  'createShareToken' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deleteCollection' : IDL.Func([IDL.Text], [], []),
  'deleteScan' : IDL.Func([IDL.Text], [], []),
  'getCollection' : IDL.Func([IDL.Text], [IDL.Opt(Collection)], ['query']),
  'getPublicDiscoveryFeed' : IDL.Func(
      [DiscoveryFilter],
      [IDL.Vec(DiscoveryScan)],
      [],
    ),
  'getScanHistory' : IDL.Func([], [IDL.Vec(ScanRecord)], ['query']),
  'getSharedScan' : IDL.Func([IDL.Text], [IDL.Opt(ScanRecord)], ['query']),
  'getUserCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
  'getUserSettings' : IDL.Func([], [IDL.Opt(UserSettings)], []),
  'getUserVideoJobs' : IDL.Func([], [IDL.Vec(VideoAnalysisJob)], []),
  'getVideoAnalysisJob' : IDL.Func([IDL.Text], [IDL.Opt(VideoAnalysisJob)], []),
  'likeDiscoveryScan' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'publishScanToDiscovery' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        AnalysisMode,
        AnalysisResult,
        IDL.Variant({ 'open' : IDL.Null, 'unlisted' : IDL.Null }),
      ],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'removeFromCollection' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveScan' : IDL.Func(
      [IDL.Text, IDL.Text, AnalysisMode, AnalysisResult],
      [IDL.Text],
      [],
    ),
  'saveScanToMyHistory' : IDL.Func([IDL.Text], [IDL.Text], []),
  'saveUserSettings' : IDL.Func([UserSettings], [], []),
  'saveVideoAnalysisJob' : IDL.Func([VideoAnalysisJob], [IDL.Text], []),
  'suggestTags' : IDL.Func(
      [TagSuggestionRequest],
      [IDL.Vec(TagSuggestion)],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unpublishScanFromDiscovery' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateVideoFrameResult' : IDL.Func(
      [IDL.Text, IDL.Nat, AnalysisResult],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AnalysisMode = IDL.Variant({
    'receipt' : IDL.Null,
    'food' : IDL.Null,
    'carFashion' : IDL.Null,
    'translation' : IDL.Null,
    'medicalReference' : IDL.Null,
    'artLandmark' : IDL.Null,
    'generic' : IDL.Null,
    'plant' : IDL.Null,
    'bookProduct' : IDL.Null,
  });
  const DetectedObject = IDL.Record({
    'name' : IDL.Text,
    'confidence' : IDL.Float64,
  });
  const WebResult = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'snippet' : IDL.Text,
  });
  const AnalysisResult = IDL.Record({
    'sceneDescription' : IDL.Text,
    'extractedText' : IDL.Text,
    'objects' : IDL.Vec(DetectedObject),
    'webResults' : IDL.Vec(WebResult),
  });
  const Timestamp = IDL.Int;
  const Collection = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'scanIds' : IDL.Vec(IDL.Text),
  });
  const DiscoveryFilter = IDL.Record({
    'sortBy' : IDL.Variant({
      'trending' : IDL.Null,
      'newest' : IDL.Null,
      'mostLiked' : IDL.Null,
    }),
    'mode' : IDL.Opt(AnalysisMode),
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'keyword' : IDL.Opt(IDL.Text),
  });
  const DiscoveryScan = IDL.Record({
    'id' : IDL.Text,
    'analysisResult' : AnalysisResult,
    'title' : IDL.Opt(IDL.Text),
    'likeCount' : IDL.Nat,
    'scanId' : IDL.Text,
    'analysisMode' : AnalysisMode,
    'ownerPrincipal' : IDL.Text,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'privacy' : IDL.Variant({ 'open' : IDL.Null, 'unlisted' : IDL.Null }),
    'viewCount' : IDL.Nat,
    'imageBase64' : IDL.Text,
  });
  const ScanRecord = IDL.Record({
    'id' : IDL.Text,
    'analysisResult' : AnalysisResult,
    'userId' : IDL.Principal,
    'mode' : AnalysisMode,
    'shareToken' : IDL.Opt(IDL.Text),
    'mimeType' : IDL.Text,
    'imageBase64' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const UserSettings = IDL.Record({
    'webSearchEnabled' : IDL.Bool,
    'historyRetentionDays' : IDL.Opt(IDL.Nat),
    'scanResultLayout' : IDL.Variant({
      'stacked' : IDL.Null,
      'compact' : IDL.Null,
      'sideBySide' : IDL.Null,
    }),
    'theme' : IDL.Variant({
      'auto' : IDL.Null,
      'dark' : IDL.Null,
      'light' : IDL.Null,
    }),
    'tagAggressiveness' : IDL.Variant({
      'aggressive' : IDL.Null,
      'subtle' : IDL.Null,
      'moderate' : IDL.Null,
    }),
    'collectionOrganizationMode' : IDL.Variant({
      'tagBased' : IDL.Null,
      'flat' : IDL.Null,
    }),
    'exportFormat' : IDL.Variant({
      'csv' : IDL.Null,
      'pdf' : IDL.Null,
      'json' : IDL.Null,
    }),
    'language' : IDL.Text,
    'resultDetailLevel' : IDL.Variant({
      'detailed' : IDL.Null,
      'compact' : IDL.Null,
      'standard' : IDL.Null,
    }),
    'defaultScanPrivacy' : IDL.Variant({
      'open' : IDL.Null,
      'unlisted' : IDL.Null,
      'onlyMe' : IDL.Null,
    }),
    'showConfidenceScores' : IDL.Bool,
    'autoSaveScans' : IDL.Bool,
  });
  const VideoFrame = IDL.Record({
    'analysisResult' : IDL.Opt(AnalysisResult),
    'imageBase64' : IDL.Text,
    'frameIndex' : IDL.Nat,
    'timestamp' : IDL.Float64,
    'processed' : IDL.Bool,
  });
  const VideoAnalysisJob = IDL.Record({
    'id' : IDL.Text,
    'frameInterval' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'processing' : IDL.Null,
      'failed' : IDL.Null,
    }),
    'frameCount' : IDL.Nat,
    'analysisMode' : AnalysisMode,
    'ownerPrincipal' : IDL.Text,
    'createdAt' : Timestamp,
    'videoName' : IDL.Text,
    'frames' : IDL.Vec(VideoFrame),
  });
  const TagSuggestionRequest = IDL.Record({
    'analysisResult' : AnalysisResult,
    'scanId' : IDL.Text,
    'existingTags' : IDL.Vec(IDL.Text),
    'aggressiveness' : IDL.Variant({
      'aggressive' : IDL.Null,
      'subtle' : IDL.Null,
      'moderate' : IDL.Null,
    }),
  });
  const TagSuggestion = IDL.Record({
    'tag' : IDL.Text,
    'source' : IDL.Variant({ 'ai' : IDL.Null, 'user' : IDL.Null }),
    'confidence' : IDL.Float64,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addScanToCollection' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'analyzeImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(AnalysisMode)],
        [AnalysisResult],
        [],
      ),
    'createCollection' : IDL.Func([IDL.Text], [IDL.Text], []),
    'createShareToken' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deleteCollection' : IDL.Func([IDL.Text], [], []),
    'deleteScan' : IDL.Func([IDL.Text], [], []),
    'getCollection' : IDL.Func([IDL.Text], [IDL.Opt(Collection)], ['query']),
    'getPublicDiscoveryFeed' : IDL.Func(
        [DiscoveryFilter],
        [IDL.Vec(DiscoveryScan)],
        [],
      ),
    'getScanHistory' : IDL.Func([], [IDL.Vec(ScanRecord)], ['query']),
    'getSharedScan' : IDL.Func([IDL.Text], [IDL.Opt(ScanRecord)], ['query']),
    'getUserCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
    'getUserSettings' : IDL.Func([], [IDL.Opt(UserSettings)], []),
    'getUserVideoJobs' : IDL.Func([], [IDL.Vec(VideoAnalysisJob)], []),
    'getVideoAnalysisJob' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VideoAnalysisJob)],
        [],
      ),
    'likeDiscoveryScan' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'publishScanToDiscovery' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          AnalysisMode,
          AnalysisResult,
          IDL.Variant({ 'open' : IDL.Null, 'unlisted' : IDL.Null }),
        ],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'removeFromCollection' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveScan' : IDL.Func(
        [IDL.Text, IDL.Text, AnalysisMode, AnalysisResult],
        [IDL.Text],
        [],
      ),
    'saveScanToMyHistory' : IDL.Func([IDL.Text], [IDL.Text], []),
    'saveUserSettings' : IDL.Func([UserSettings], [], []),
    'saveVideoAnalysisJob' : IDL.Func([VideoAnalysisJob], [IDL.Text], []),
    'suggestTags' : IDL.Func(
        [TagSuggestionRequest],
        [IDL.Vec(TagSuggestion)],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unpublishScanFromDiscovery' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateVideoFrameResult' : IDL.Func(
        [IDL.Text, IDL.Nat, AnalysisResult],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };