/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnalysisMode = { 'receipt' : null } |
  { 'food' : null } |
  { 'carFashion' : null } |
  { 'translation' : null } |
  { 'medicalReference' : null } |
  { 'artLandmark' : null } |
  { 'generic' : null } |
  { 'plant' : null } |
  { 'bookProduct' : null };
export interface AnalysisResult {
  'sceneDescription' : string,
  'extractedText' : string,
  'objects' : Array<DetectedObject>,
  'webResults' : Array<WebResult>,
}
export interface Collection {
  'id' : string,
  'userId' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'scanIds' : Array<string>,
}
export interface DetectedObject { 'name' : string, 'confidence' : number }
export interface DiscoveryFilter {
  'sortBy' : { 'trending' : null } |
    { 'newest' : null } |
    { 'mostLiked' : null },
  'mode' : [] | [AnalysisMode],
  'offset' : bigint,
  'limit' : bigint,
  'keyword' : [] | [string],
}
export interface DiscoveryScan {
  'id' : string,
  'analysisResult' : AnalysisResult,
  'title' : [] | [string],
  'likeCount' : bigint,
  'scanId' : string,
  'analysisMode' : AnalysisMode,
  'ownerPrincipal' : string,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'privacy' : { 'open' : null } |
    { 'unlisted' : null },
  'viewCount' : bigint,
  'imageBase64' : string,
}
export interface ScanRecord {
  'id' : string,
  'analysisResult' : AnalysisResult,
  'userId' : Principal,
  'mode' : AnalysisMode,
  'shareToken' : [] | [string],
  'mimeType' : string,
  'imageBase64' : string,
  'timestamp' : Timestamp,
}
export interface TagSuggestion {
  'tag' : string,
  'source' : { 'ai' : null } |
    { 'user' : null },
  'confidence' : number,
}
export interface TagSuggestionRequest {
  'analysisResult' : AnalysisResult,
  'scanId' : string,
  'existingTags' : Array<string>,
  'aggressiveness' : { 'aggressive' : null } |
    { 'subtle' : null } |
    { 'moderate' : null },
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserSettings {
  'webSearchEnabled' : boolean,
  'historyRetentionDays' : [] | [bigint],
  'scanResultLayout' : { 'stacked' : null } |
    { 'compact' : null } |
    { 'sideBySide' : null },
  'theme' : { 'auto' : null } |
    { 'dark' : null } |
    { 'light' : null },
  'tagAggressiveness' : { 'aggressive' : null } |
    { 'subtle' : null } |
    { 'moderate' : null },
  'collectionOrganizationMode' : { 'tagBased' : null } |
    { 'flat' : null },
  'exportFormat' : { 'csv' : null } |
    { 'pdf' : null } |
    { 'json' : null },
  'language' : string,
  'resultDetailLevel' : { 'detailed' : null } |
    { 'compact' : null } |
    { 'standard' : null },
  'defaultScanPrivacy' : { 'open' : null } |
    { 'unlisted' : null } |
    { 'onlyMe' : null },
  'showConfidenceScores' : boolean,
  'autoSaveScans' : boolean,
}
export interface VideoAnalysisJob {
  'id' : string,
  'frameInterval' : bigint,
  'status' : { 'pending' : null } |
    { 'completed' : null } |
    { 'processing' : null } |
    { 'failed' : null },
  'frameCount' : bigint,
  'analysisMode' : AnalysisMode,
  'ownerPrincipal' : string,
  'createdAt' : Timestamp,
  'videoName' : string,
  'frames' : Array<VideoFrame>,
}
export interface VideoFrame {
  'analysisResult' : [] | [AnalysisResult],
  'imageBase64' : string,
  'frameIndex' : bigint,
  'timestamp' : number,
  'processed' : boolean,
}
export interface WebResult {
  'url' : string,
  'title' : string,
  'snippet' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addScanToCollection' : ActorMethod<[string, string], undefined>,
  'analyzeImage' : ActorMethod<
    [string, string, [] | [AnalysisMode]],
    AnalysisResult
  >,
  'createCollection' : ActorMethod<[string], string>,
  'createShareToken' : ActorMethod<[string], string>,
  'deleteCollection' : ActorMethod<[string], undefined>,
  'deleteScan' : ActorMethod<[string], undefined>,
  'getCollection' : ActorMethod<[string], [] | [Collection]>,
  'getPublicDiscoveryFeed' : ActorMethod<
    [DiscoveryFilter],
    Array<DiscoveryScan>
  >,
  'getScanHistory' : ActorMethod<[], Array<ScanRecord>>,
  'getSharedScan' : ActorMethod<[string], [] | [ScanRecord]>,
  'getUserCollections' : ActorMethod<[], Array<Collection>>,
  'getUserSettings' : ActorMethod<[], [] | [UserSettings]>,
  'getUserVideoJobs' : ActorMethod<[], Array<VideoAnalysisJob>>,
  'getVideoAnalysisJob' : ActorMethod<[string], [] | [VideoAnalysisJob]>,
  'likeDiscoveryScan' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'publishScanToDiscovery' : ActorMethod<
    [
      string,
      [] | [string],
      Array<string>,
      string,
      AnalysisMode,
      AnalysisResult,
      { 'open' : null } |
        { 'unlisted' : null },
    ],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'removeFromCollection' : ActorMethod<[string, string], undefined>,
  'saveScan' : ActorMethod<
    [string, string, AnalysisMode, AnalysisResult],
    string
  >,
  'saveScanToMyHistory' : ActorMethod<[string], string>,
  'saveUserSettings' : ActorMethod<[UserSettings], undefined>,
  'saveVideoAnalysisJob' : ActorMethod<[VideoAnalysisJob], string>,
  'suggestTags' : ActorMethod<[TagSuggestionRequest], Array<TagSuggestion>>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unpublishScanFromDiscovery' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateVideoFrameResult' : ActorMethod<
    [string, bigint, AnalysisResult],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];