/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WebResult {
    url: string;
    title: string;
    snippet: string;
}
export interface DiscoveryScan {
    id: string;
    analysisResult: AnalysisResult;
    title?: string;
    likeCount: bigint;
    scanId: string;
    analysisMode: AnalysisMode;
    ownerPrincipal: string;
    createdAt: Timestamp;
    tags: Array<string>;
    privacy: Variant_open_unlisted;
    viewCount: bigint;
    imageBase64: string;
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TagSuggestionRequest {
    analysisResult: AnalysisResult;
    scanId: string;
    existingTags: Array<string>;
    aggressiveness: Variant_aggressive_subtle_moderate;
}
export interface ScanRecord {
    id: string;
    analysisResult: AnalysisResult;
    userId: Principal;
    mode: AnalysisMode;
    shareToken?: string;
    mimeType: string;
    imageBase64: string;
    timestamp: Timestamp;
}
export interface http_header {
    value: string;
    name: string;
}
export interface VideoFrame {
    analysisResult?: AnalysisResult;
    imageBase64: string;
    frameIndex: bigint;
    timestamp: number;
    processed: boolean;
}
export interface TagSuggestion {
    tag: string;
    source: Variant_ai_user;
    confidence: number;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Collection {
    id: string;
    userId: Principal;
    name: string;
    createdAt: Timestamp;
    scanIds: Array<string>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface VideoAnalysisJob {
    id: string;
    frameInterval: bigint;
    status: Variant_pending_completed_processing_failed;
    frameCount: bigint;
    analysisMode: AnalysisMode;
    ownerPrincipal: string;
    createdAt: Timestamp;
    videoName: string;
    frames: Array<VideoFrame>;
}
export interface UserSettings {
    webSearchEnabled: boolean;
    historyRetentionDays?: bigint;
    scanResultLayout: Variant_stacked_compact_sideBySide;
    theme: Variant_auto_dark_light;
    tagAggressiveness: Variant_aggressive_subtle_moderate;
    collectionOrganizationMode: Variant_tagBased_flat;
    exportFormat: Variant_csv_pdf_json;
    language: string;
    resultDetailLevel: Variant_detailed_compact_standard;
    defaultScanPrivacy: Variant_open_unlisted_onlyMe;
    showConfidenceScores: boolean;
    autoSaveScans: boolean;
}
export interface DiscoveryFilter {
    sortBy: Variant_trending_newest_mostLiked;
    mode?: AnalysisMode;
    offset: bigint;
    limit: bigint;
    keyword?: string;
}
export interface DetectedObject {
    name: string;
    confidence: number;
}
export interface AnalysisResult {
    sceneDescription: string;
    extractedText: string;
    objects: Array<DetectedObject>;
    webResults: Array<WebResult>;
}
export enum AnalysisMode {
    receipt = "receipt",
    food = "food",
    carFashion = "carFashion",
    translation = "translation",
    medicalReference = "medicalReference",
    artLandmark = "artLandmark",
    generic = "generic",
    plant = "plant",
    bookProduct = "bookProduct"
}
export enum Variant_aggressive_subtle_moderate {
    aggressive = "aggressive",
    subtle = "subtle",
    moderate = "moderate"
}
export enum Variant_ai_user {
    ai = "ai",
    user = "user"
}
export enum Variant_auto_dark_light {
    auto = "auto",
    dark = "dark",
    light = "light"
}
export enum Variant_csv_pdf_json {
    csv = "csv",
    pdf = "pdf",
    json = "json"
}
export enum Variant_detailed_compact_standard {
    detailed = "detailed",
    compact = "compact",
    standard = "standard"
}
export enum Variant_open_unlisted {
    open = "open",
    unlisted = "unlisted"
}
export enum Variant_open_unlisted_onlyMe {
    open = "open",
    unlisted = "unlisted",
    onlyMe = "onlyMe"
}
export enum Variant_pending_completed_processing_failed {
    pending = "pending",
    completed = "completed",
    processing = "processing",
    failed = "failed"
}
export enum Variant_stacked_compact_sideBySide {
    stacked = "stacked",
    compact = "compact",
    sideBySide = "sideBySide"
}
export enum Variant_tagBased_flat {
    tagBased = "tagBased",
    flat = "flat"
}
export enum Variant_trending_newest_mostLiked {
    trending = "trending",
    newest = "newest",
    mostLiked = "mostLiked"
}
export interface backendInterface {
    addScanToCollection(collectionId: string, scanId: string): Promise<void>;
    analyzeImage(imageBase64: string, mimeType: string, mode: AnalysisMode | null): Promise<AnalysisResult>;
    createCollection(name: string): Promise<string>;
    createShareToken(scanId: string): Promise<string>;
    deleteCollection(collectionId: string): Promise<void>;
    deleteScan(scanId: string): Promise<void>;
    getCollection(collectionId: string): Promise<Collection | null>;
    getPublicDiscoveryFeed(filter: DiscoveryFilter): Promise<Array<DiscoveryScan>>;
    getScanHistory(): Promise<Array<ScanRecord>>;
    getSharedScan(token: string): Promise<ScanRecord | null>;
    getUserCollections(): Promise<Array<Collection>>;
    getUserSettings(): Promise<UserSettings | null>;
    getUserVideoJobs(): Promise<Array<VideoAnalysisJob>>;
    getVideoAnalysisJob(jobId: string): Promise<VideoAnalysisJob | null>;
    likeDiscoveryScan(discoveryId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    publishScanToDiscovery(scanId: string, title: string | null, tags: Array<string>, imageBase64: string, analysisMode: AnalysisMode, analysisResult: AnalysisResult, privacy: Variant_open_unlisted): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    removeFromCollection(collectionId: string, scanId: string): Promise<void>;
    saveScan(imageBase64: string, mimeType: string, mode: AnalysisMode, analysisResult: AnalysisResult): Promise<string>;
    saveScanToMyHistory(sharedToken: string): Promise<string>;
    saveUserSettings(settings: UserSettings): Promise<void>;
    saveVideoAnalysisJob(job: VideoAnalysisJob): Promise<string>;
    suggestTags(request: TagSuggestionRequest): Promise<Array<TagSuggestion>>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unpublishScanFromDiscovery(discoveryId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateVideoFrameResult(jobId: string, frameIndex: bigint, result: AnalysisResult): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { AnalysisMode as _AnalysisMode, AnalysisResult as _AnalysisResult, Collection as _Collection, DiscoveryFilter as _DiscoveryFilter, DiscoveryScan as _DiscoveryScan, ScanRecord as _ScanRecord, TagSuggestion as _TagSuggestion, TagSuggestionRequest as _TagSuggestionRequest, Timestamp as _Timestamp, UserSettings as _UserSettings, VideoAnalysisJob as _VideoAnalysisJob, VideoFrame as _VideoFrame } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addScanToCollection(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addScanToCollection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addScanToCollection(arg0, arg1);
            return result;
        }
    }
    async analyzeImage(arg0: string, arg1: string, arg2: AnalysisMode | null): Promise<AnalysisResult> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeImage(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeImage(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createCollection(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCollection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCollection(arg0);
            return result;
        }
    }
    async createShareToken(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createShareToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShareToken(arg0);
            return result;
        }
    }
    async deleteCollection(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCollection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCollection(arg0);
            return result;
        }
    }
    async deleteScan(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScan(arg0);
            return result;
        }
    }
    async getCollection(arg0: string): Promise<Collection | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollection(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollection(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicDiscoveryFeed(arg0: DiscoveryFilter): Promise<Array<DiscoveryScan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicDiscoveryFeed(to_candid_DiscoveryFilter_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicDiscoveryFeed(to_candid_DiscoveryFilter_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScanHistory(): Promise<Array<ScanRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScanHistory();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScanHistory();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSharedScan(arg0: string): Promise<ScanRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSharedScan(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSharedScan(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserCollections(): Promise<Array<Collection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCollections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCollections();
            return result;
        }
    }
    async getUserSettings(): Promise<UserSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSettings();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSettings();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserVideoJobs(): Promise<Array<VideoAnalysisJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserVideoJobs();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserVideoJobs();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoAnalysisJob(arg0: string): Promise<VideoAnalysisJob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoAnalysisJob(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoAnalysisJob(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async likeDiscoveryScan(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.likeDiscoveryScan(arg0);
                return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeDiscoveryScan(arg0);
            return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async publishScanToDiscovery(arg0: string, arg1: string | null, arg2: Array<string>, arg3: string, arg4: AnalysisMode, arg5: AnalysisResult, arg6: Variant_open_unlisted): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.publishScanToDiscovery(arg0, to_candid_opt_n40(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_AnalysisMode_n2(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_variant_n41(this._uploadFile, this._downloadFile, arg6));
                return from_candid_variant_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishScanToDiscovery(arg0, to_candid_opt_n40(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_AnalysisMode_n2(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_variant_n41(this._uploadFile, this._downloadFile, arg6));
            return from_candid_variant_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromCollection(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCollection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCollection(arg0, arg1);
            return result;
        }
    }
    async saveScan(arg0: string, arg1: string, arg2: AnalysisMode, arg3: AnalysisResult): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveScan(arg0, arg1, to_candid_AnalysisMode_n2(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveScan(arg0, arg1, to_candid_AnalysisMode_n2(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async saveScanToMyHistory(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveScanToMyHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveScanToMyHistory(arg0);
            return result;
        }
    }
    async saveUserSettings(arg0: UserSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserSettings(to_candid_UserSettings_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserSettings(to_candid_UserSettings_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveVideoAnalysisJob(arg0: VideoAnalysisJob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveVideoAnalysisJob(to_candid_VideoAnalysisJob_n52(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveVideoAnalysisJob(to_candid_VideoAnalysisJob_n52(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async suggestTags(arg0: TagSuggestionRequest): Promise<Array<TagSuggestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.suggestTags(to_candid_TagSuggestionRequest_n58(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suggestTags(to_candid_TagSuggestionRequest_n58(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unpublishScanFromDiscovery(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.unpublishScanFromDiscovery(arg0);
                return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpublishScanFromDiscovery(arg0);
            return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateVideoFrameResult(arg0: string, arg1: bigint, arg2: AnalysisResult): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideoFrameResult(arg0, arg1, arg2);
                return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideoFrameResult(arg0, arg1, arg2);
            return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AnalysisMode_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisMode): AnalysisMode {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_DiscoveryScan_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiscoveryScan): DiscoveryScan {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ScanRecord_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScanRecord): ScanRecord {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_TagSuggestion_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TagSuggestion): TagSuggestion {
    return from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_UserSettings_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserSettings): UserSettings {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_VideoAnalysisJob_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoAnalysisJob): VideoAnalysisJob {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_VideoFrame_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoFrame): VideoFrame {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ScanRecord]): ScanRecord | null {
    return value.length === 0 ? null : from_candid_ScanRecord_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserSettings]): UserSettings | null {
    return value.length === 0 ? null : from_candid_UserSettings_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AnalysisResult]): AnalysisResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoAnalysisJob]): VideoAnalysisJob | null {
    return value.length === 0 ? null : from_candid_VideoAnalysisJob_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Collection]): Collection | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    analysisResult: _AnalysisResult;
    title: [] | [string];
    likeCount: bigint;
    scanId: string;
    analysisMode: _AnalysisMode;
    ownerPrincipal: string;
    createdAt: _Timestamp;
    tags: Array<string>;
    privacy: {
        open: null;
    } | {
        unlisted: null;
    };
    viewCount: bigint;
    imageBase64: string;
}): {
    id: string;
    analysisResult: AnalysisResult;
    title?: string;
    likeCount: bigint;
    scanId: string;
    analysisMode: AnalysisMode;
    ownerPrincipal: string;
    createdAt: Timestamp;
    tags: Array<string>;
    privacy: Variant_open_unlisted;
    viewCount: bigint;
    imageBase64: string;
} {
    return {
        id: value.id,
        analysisResult: value.analysisResult,
        title: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.title)),
        likeCount: value.likeCount,
        scanId: value.scanId,
        analysisMode: from_candid_AnalysisMode_n12(_uploadFile, _downloadFile, value.analysisMode),
        ownerPrincipal: value.ownerPrincipal,
        createdAt: value.createdAt,
        tags: value.tags,
        privacy: from_candid_variant_n14(_uploadFile, _downloadFile, value.privacy),
        viewCount: value.viewCount,
        imageBase64: value.imageBase64
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    analysisResult: _AnalysisResult;
    userId: Principal;
    mode: _AnalysisMode;
    shareToken: [] | [string];
    mimeType: string;
    imageBase64: string;
    timestamp: _Timestamp;
}): {
    id: string;
    analysisResult: AnalysisResult;
    userId: Principal;
    mode: AnalysisMode;
    shareToken?: string;
    mimeType: string;
    imageBase64: string;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        analysisResult: value.analysisResult,
        userId: value.userId,
        mode: from_candid_AnalysisMode_n12(_uploadFile, _downloadFile, value.mode),
        shareToken: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.shareToken)),
        mimeType: value.mimeType,
        imageBase64: value.imageBase64,
        timestamp: value.timestamp
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    webSearchEnabled: boolean;
    historyRetentionDays: [] | [bigint];
    scanResultLayout: {
        stacked: null;
    } | {
        compact: null;
    } | {
        sideBySide: null;
    };
    theme: {
        auto: null;
    } | {
        dark: null;
    } | {
        light: null;
    };
    tagAggressiveness: {
        aggressive: null;
    } | {
        subtle: null;
    } | {
        moderate: null;
    };
    collectionOrganizationMode: {
        tagBased: null;
    } | {
        flat: null;
    };
    exportFormat: {
        csv: null;
    } | {
        pdf: null;
    } | {
        json: null;
    };
    language: string;
    resultDetailLevel: {
        detailed: null;
    } | {
        compact: null;
    } | {
        standard: null;
    };
    defaultScanPrivacy: {
        open: null;
    } | {
        unlisted: null;
    } | {
        onlyMe: null;
    };
    showConfidenceScores: boolean;
    autoSaveScans: boolean;
}): {
    webSearchEnabled: boolean;
    historyRetentionDays?: bigint;
    scanResultLayout: Variant_stacked_compact_sideBySide;
    theme: Variant_auto_dark_light;
    tagAggressiveness: Variant_aggressive_subtle_moderate;
    collectionOrganizationMode: Variant_tagBased_flat;
    exportFormat: Variant_csv_pdf_json;
    language: string;
    resultDetailLevel: Variant_detailed_compact_standard;
    defaultScanPrivacy: Variant_open_unlisted_onlyMe;
    showConfidenceScores: boolean;
    autoSaveScans: boolean;
} {
    return {
        webSearchEnabled: value.webSearchEnabled,
        historyRetentionDays: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.historyRetentionDays)),
        scanResultLayout: from_candid_variant_n23(_uploadFile, _downloadFile, value.scanResultLayout),
        theme: from_candid_variant_n24(_uploadFile, _downloadFile, value.theme),
        tagAggressiveness: from_candid_variant_n25(_uploadFile, _downloadFile, value.tagAggressiveness),
        collectionOrganizationMode: from_candid_variant_n26(_uploadFile, _downloadFile, value.collectionOrganizationMode),
        exportFormat: from_candid_variant_n27(_uploadFile, _downloadFile, value.exportFormat),
        language: value.language,
        resultDetailLevel: from_candid_variant_n28(_uploadFile, _downloadFile, value.resultDetailLevel),
        defaultScanPrivacy: from_candid_variant_n29(_uploadFile, _downloadFile, value.defaultScanPrivacy),
        showConfidenceScores: value.showConfidenceScores,
        autoSaveScans: value.autoSaveScans
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    frameInterval: bigint;
    status: {
        pending: null;
    } | {
        completed: null;
    } | {
        processing: null;
    } | {
        failed: null;
    };
    frameCount: bigint;
    analysisMode: _AnalysisMode;
    ownerPrincipal: string;
    createdAt: _Timestamp;
    videoName: string;
    frames: Array<_VideoFrame>;
}): {
    id: string;
    frameInterval: bigint;
    status: Variant_pending_completed_processing_failed;
    frameCount: bigint;
    analysisMode: AnalysisMode;
    ownerPrincipal: string;
    createdAt: Timestamp;
    videoName: string;
    frames: Array<VideoFrame>;
} {
    return {
        id: value.id,
        frameInterval: value.frameInterval,
        status: from_candid_variant_n33(_uploadFile, _downloadFile, value.status),
        frameCount: value.frameCount,
        analysisMode: from_candid_AnalysisMode_n12(_uploadFile, _downloadFile, value.analysisMode),
        ownerPrincipal: value.ownerPrincipal,
        createdAt: value.createdAt,
        videoName: value.videoName,
        frames: from_candid_vec_n34(_uploadFile, _downloadFile, value.frames)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    analysisResult: [] | [_AnalysisResult];
    imageBase64: string;
    frameIndex: bigint;
    timestamp: number;
    processed: boolean;
}): {
    analysisResult?: AnalysisResult;
    imageBase64: string;
    frameIndex: bigint;
    timestamp: number;
    processed: boolean;
} {
    return {
        analysisResult: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.analysisResult)),
        imageBase64: value.imageBase64,
        frameIndex: value.frameIndex,
        timestamp: value.timestamp,
        processed: value.processed
    };
}
function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tag: string;
    source: {
        ai: null;
    } | {
        user: null;
    };
    confidence: number;
}): {
    tag: string;
    source: Variant_ai_user;
    confidence: number;
} {
    return {
        tag: value.tag,
        source: from_candid_variant_n63(_uploadFile, _downloadFile, value.source),
        confidence: value.confidence
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    receipt: null;
} | {
    food: null;
} | {
    carFashion: null;
} | {
    translation: null;
} | {
    medicalReference: null;
} | {
    artLandmark: null;
} | {
    generic: null;
} | {
    plant: null;
} | {
    bookProduct: null;
}): AnalysisMode {
    return "receipt" in value ? AnalysisMode.receipt : "food" in value ? AnalysisMode.food : "carFashion" in value ? AnalysisMode.carFashion : "translation" in value ? AnalysisMode.translation : "medicalReference" in value ? AnalysisMode.medicalReference : "artLandmark" in value ? AnalysisMode.artLandmark : "generic" in value ? AnalysisMode.generic : "plant" in value ? AnalysisMode.plant : "bookProduct" in value ? AnalysisMode.bookProduct : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    open: null;
} | {
    unlisted: null;
}): Variant_open_unlisted {
    return "open" in value ? Variant_open_unlisted.open : "unlisted" in value ? Variant_open_unlisted.unlisted : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stacked: null;
} | {
    compact: null;
} | {
    sideBySide: null;
}): Variant_stacked_compact_sideBySide {
    return "stacked" in value ? Variant_stacked_compact_sideBySide.stacked : "compact" in value ? Variant_stacked_compact_sideBySide.compact : "sideBySide" in value ? Variant_stacked_compact_sideBySide.sideBySide : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    auto: null;
} | {
    dark: null;
} | {
    light: null;
}): Variant_auto_dark_light {
    return "auto" in value ? Variant_auto_dark_light.auto : "dark" in value ? Variant_auto_dark_light.dark : "light" in value ? Variant_auto_dark_light.light : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aggressive: null;
} | {
    subtle: null;
} | {
    moderate: null;
}): Variant_aggressive_subtle_moderate {
    return "aggressive" in value ? Variant_aggressive_subtle_moderate.aggressive : "subtle" in value ? Variant_aggressive_subtle_moderate.subtle : "moderate" in value ? Variant_aggressive_subtle_moderate.moderate : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tagBased: null;
} | {
    flat: null;
}): Variant_tagBased_flat {
    return "tagBased" in value ? Variant_tagBased_flat.tagBased : "flat" in value ? Variant_tagBased_flat.flat : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    csv: null;
} | {
    pdf: null;
} | {
    json: null;
}): Variant_csv_pdf_json {
    return "csv" in value ? Variant_csv_pdf_json.csv : "pdf" in value ? Variant_csv_pdf_json.pdf : "json" in value ? Variant_csv_pdf_json.json : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    detailed: null;
} | {
    compact: null;
} | {
    standard: null;
}): Variant_detailed_compact_standard {
    return "detailed" in value ? Variant_detailed_compact_standard.detailed : "compact" in value ? Variant_detailed_compact_standard.compact : "standard" in value ? Variant_detailed_compact_standard.standard : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    open: null;
} | {
    unlisted: null;
} | {
    onlyMe: null;
}): Variant_open_unlisted_onlyMe {
    return "open" in value ? Variant_open_unlisted_onlyMe.open : "unlisted" in value ? Variant_open_unlisted_onlyMe.unlisted : "onlyMe" in value ? Variant_open_unlisted_onlyMe.onlyMe : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    processing: null;
} | {
    failed: null;
}): Variant_pending_completed_processing_failed {
    return "pending" in value ? Variant_pending_completed_processing_failed.pending : "completed" in value ? Variant_pending_completed_processing_failed.completed : "processing" in value ? Variant_pending_completed_processing_failed.processing : "failed" in value ? Variant_pending_completed_processing_failed.failed : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ai: null;
} | {
    user: null;
}): Variant_ai_user {
    return "ai" in value ? Variant_ai_user.ai : "user" in value ? Variant_ai_user.user : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ScanRecord>): Array<ScanRecord> {
    return value.map((x)=>from_candid_ScanRecord_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoAnalysisJob>): Array<VideoAnalysisJob> {
    return value.map((x)=>from_candid_VideoAnalysisJob_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoFrame>): Array<VideoFrame> {
    return value.map((x)=>from_candid_VideoFrame_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TagSuggestion>): Array<TagSuggestion> {
    return value.map((x)=>from_candid_TagSuggestion_n61(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DiscoveryScan>): Array<DiscoveryScan> {
    return value.map((x)=>from_candid_DiscoveryScan_n9(_uploadFile, _downloadFile, x));
}
function to_candid_AnalysisMode_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalysisMode): _AnalysisMode {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_DiscoveryFilter_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscoveryFilter): _DiscoveryFilter {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TagSuggestionRequest_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TagSuggestionRequest): _TagSuggestionRequest {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_UserSettings_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserSettings): _UserSettings {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_VideoAnalysisJob_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoAnalysisJob): _VideoAnalysisJob {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_VideoFrame_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoFrame): _VideoFrame {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalysisMode | null): [] | [_AnalysisMode] {
    return value === null ? candid_none() : candid_some(to_candid_AnalysisMode_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    webSearchEnabled: boolean;
    historyRetentionDays?: bigint;
    scanResultLayout: Variant_stacked_compact_sideBySide;
    theme: Variant_auto_dark_light;
    tagAggressiveness: Variant_aggressive_subtle_moderate;
    collectionOrganizationMode: Variant_tagBased_flat;
    exportFormat: Variant_csv_pdf_json;
    language: string;
    resultDetailLevel: Variant_detailed_compact_standard;
    defaultScanPrivacy: Variant_open_unlisted_onlyMe;
    showConfidenceScores: boolean;
    autoSaveScans: boolean;
}): {
    webSearchEnabled: boolean;
    historyRetentionDays: [] | [bigint];
    scanResultLayout: {
        stacked: null;
    } | {
        compact: null;
    } | {
        sideBySide: null;
    };
    theme: {
        auto: null;
    } | {
        dark: null;
    } | {
        light: null;
    };
    tagAggressiveness: {
        aggressive: null;
    } | {
        subtle: null;
    } | {
        moderate: null;
    };
    collectionOrganizationMode: {
        tagBased: null;
    } | {
        flat: null;
    };
    exportFormat: {
        csv: null;
    } | {
        pdf: null;
    } | {
        json: null;
    };
    language: string;
    resultDetailLevel: {
        detailed: null;
    } | {
        compact: null;
    } | {
        standard: null;
    };
    defaultScanPrivacy: {
        open: null;
    } | {
        unlisted: null;
    } | {
        onlyMe: null;
    };
    showConfidenceScores: boolean;
    autoSaveScans: boolean;
} {
    return {
        webSearchEnabled: value.webSearchEnabled,
        historyRetentionDays: value.historyRetentionDays ? candid_some(value.historyRetentionDays) : candid_none(),
        scanResultLayout: to_candid_variant_n45(_uploadFile, _downloadFile, value.scanResultLayout),
        theme: to_candid_variant_n46(_uploadFile, _downloadFile, value.theme),
        tagAggressiveness: to_candid_variant_n47(_uploadFile, _downloadFile, value.tagAggressiveness),
        collectionOrganizationMode: to_candid_variant_n48(_uploadFile, _downloadFile, value.collectionOrganizationMode),
        exportFormat: to_candid_variant_n49(_uploadFile, _downloadFile, value.exportFormat),
        language: value.language,
        resultDetailLevel: to_candid_variant_n50(_uploadFile, _downloadFile, value.resultDetailLevel),
        defaultScanPrivacy: to_candid_variant_n51(_uploadFile, _downloadFile, value.defaultScanPrivacy),
        showConfidenceScores: value.showConfidenceScores,
        autoSaveScans: value.autoSaveScans
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    frameInterval: bigint;
    status: Variant_pending_completed_processing_failed;
    frameCount: bigint;
    analysisMode: AnalysisMode;
    ownerPrincipal: string;
    createdAt: Timestamp;
    videoName: string;
    frames: Array<VideoFrame>;
}): {
    id: string;
    frameInterval: bigint;
    status: {
        pending: null;
    } | {
        completed: null;
    } | {
        processing: null;
    } | {
        failed: null;
    };
    frameCount: bigint;
    analysisMode: _AnalysisMode;
    ownerPrincipal: string;
    createdAt: _Timestamp;
    videoName: string;
    frames: Array<_VideoFrame>;
} {
    return {
        id: value.id,
        frameInterval: value.frameInterval,
        status: to_candid_variant_n54(_uploadFile, _downloadFile, value.status),
        frameCount: value.frameCount,
        analysisMode: to_candid_AnalysisMode_n2(_uploadFile, _downloadFile, value.analysisMode),
        ownerPrincipal: value.ownerPrincipal,
        createdAt: value.createdAt,
        videoName: value.videoName,
        frames: to_candid_vec_n55(_uploadFile, _downloadFile, value.frames)
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    analysisResult?: AnalysisResult;
    imageBase64: string;
    frameIndex: bigint;
    timestamp: number;
    processed: boolean;
}): {
    analysisResult: [] | [_AnalysisResult];
    imageBase64: string;
    frameIndex: bigint;
    timestamp: number;
    processed: boolean;
} {
    return {
        analysisResult: value.analysisResult ? candid_some(value.analysisResult) : candid_none(),
        imageBase64: value.imageBase64,
        frameIndex: value.frameIndex,
        timestamp: value.timestamp,
        processed: value.processed
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    analysisResult: AnalysisResult;
    scanId: string;
    existingTags: Array<string>;
    aggressiveness: Variant_aggressive_subtle_moderate;
}): {
    analysisResult: _AnalysisResult;
    scanId: string;
    existingTags: Array<string>;
    aggressiveness: {
        aggressive: null;
    } | {
        subtle: null;
    } | {
        moderate: null;
    };
} {
    return {
        analysisResult: value.analysisResult,
        scanId: value.scanId,
        existingTags: value.existingTags,
        aggressiveness: to_candid_variant_n47(_uploadFile, _downloadFile, value.aggressiveness)
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sortBy: Variant_trending_newest_mostLiked;
    mode?: AnalysisMode;
    offset: bigint;
    limit: bigint;
    keyword?: string;
}): {
    sortBy: {
        trending: null;
    } | {
        newest: null;
    } | {
        mostLiked: null;
    };
    mode: [] | [_AnalysisMode];
    offset: bigint;
    limit: bigint;
    keyword: [] | [string];
} {
    return {
        sortBy: to_candid_variant_n7(_uploadFile, _downloadFile, value.sortBy),
        mode: value.mode ? candid_some(to_candid_AnalysisMode_n2(_uploadFile, _downloadFile, value.mode)) : candid_none(),
        offset: value.offset,
        limit: value.limit,
        keyword: value.keyword ? candid_some(value.keyword) : candid_none()
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalysisMode): {
    receipt: null;
} | {
    food: null;
} | {
    carFashion: null;
} | {
    translation: null;
} | {
    medicalReference: null;
} | {
    artLandmark: null;
} | {
    generic: null;
} | {
    plant: null;
} | {
    bookProduct: null;
} {
    return value == AnalysisMode.receipt ? {
        receipt: null
    } : value == AnalysisMode.food ? {
        food: null
    } : value == AnalysisMode.carFashion ? {
        carFashion: null
    } : value == AnalysisMode.translation ? {
        translation: null
    } : value == AnalysisMode.medicalReference ? {
        medicalReference: null
    } : value == AnalysisMode.artLandmark ? {
        artLandmark: null
    } : value == AnalysisMode.generic ? {
        generic: null
    } : value == AnalysisMode.plant ? {
        plant: null
    } : value == AnalysisMode.bookProduct ? {
        bookProduct: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_open_unlisted): {
    open: null;
} | {
    unlisted: null;
} {
    return value == Variant_open_unlisted.open ? {
        open: null
    } : value == Variant_open_unlisted.unlisted ? {
        unlisted: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_stacked_compact_sideBySide): {
    stacked: null;
} | {
    compact: null;
} | {
    sideBySide: null;
} {
    return value == Variant_stacked_compact_sideBySide.stacked ? {
        stacked: null
    } : value == Variant_stacked_compact_sideBySide.compact ? {
        compact: null
    } : value == Variant_stacked_compact_sideBySide.sideBySide ? {
        sideBySide: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_auto_dark_light): {
    auto: null;
} | {
    dark: null;
} | {
    light: null;
} {
    return value == Variant_auto_dark_light.auto ? {
        auto: null
    } : value == Variant_auto_dark_light.dark ? {
        dark: null
    } : value == Variant_auto_dark_light.light ? {
        light: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_aggressive_subtle_moderate): {
    aggressive: null;
} | {
    subtle: null;
} | {
    moderate: null;
} {
    return value == Variant_aggressive_subtle_moderate.aggressive ? {
        aggressive: null
    } : value == Variant_aggressive_subtle_moderate.subtle ? {
        subtle: null
    } : value == Variant_aggressive_subtle_moderate.moderate ? {
        moderate: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_tagBased_flat): {
    tagBased: null;
} | {
    flat: null;
} {
    return value == Variant_tagBased_flat.tagBased ? {
        tagBased: null
    } : value == Variant_tagBased_flat.flat ? {
        flat: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_csv_pdf_json): {
    csv: null;
} | {
    pdf: null;
} | {
    json: null;
} {
    return value == Variant_csv_pdf_json.csv ? {
        csv: null
    } : value == Variant_csv_pdf_json.pdf ? {
        pdf: null
    } : value == Variant_csv_pdf_json.json ? {
        json: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_detailed_compact_standard): {
    detailed: null;
} | {
    compact: null;
} | {
    standard: null;
} {
    return value == Variant_detailed_compact_standard.detailed ? {
        detailed: null
    } : value == Variant_detailed_compact_standard.compact ? {
        compact: null
    } : value == Variant_detailed_compact_standard.standard ? {
        standard: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_open_unlisted_onlyMe): {
    open: null;
} | {
    unlisted: null;
} | {
    onlyMe: null;
} {
    return value == Variant_open_unlisted_onlyMe.open ? {
        open: null
    } : value == Variant_open_unlisted_onlyMe.unlisted ? {
        unlisted: null
    } : value == Variant_open_unlisted_onlyMe.onlyMe ? {
        onlyMe: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_completed_processing_failed): {
    pending: null;
} | {
    completed: null;
} | {
    processing: null;
} | {
    failed: null;
} {
    return value == Variant_pending_completed_processing_failed.pending ? {
        pending: null
    } : value == Variant_pending_completed_processing_failed.completed ? {
        completed: null
    } : value == Variant_pending_completed_processing_failed.processing ? {
        processing: null
    } : value == Variant_pending_completed_processing_failed.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_trending_newest_mostLiked): {
    trending: null;
} | {
    newest: null;
} | {
    mostLiked: null;
} {
    return value == Variant_trending_newest_mostLiked.trending ? {
        trending: null
    } : value == Variant_trending_newest_mostLiked.newest ? {
        newest: null
    } : value == Variant_trending_newest_mostLiked.mostLiked ? {
        mostLiked: null
    } : value;
}
function to_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<VideoFrame>): Array<_VideoFrame> {
    return value.map((x)=>to_candid_VideoFrame_n56(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
